apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluesky-firehose
  namespace: bluesky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluesky-firehose
  template:
    metadata:
      labels:
        app: bluesky-firehose
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: aggregator
          image: harbor.allocsoc.net/bluesky/poc:b98489e3bf9871829a05bdde3543cbcd38b7371d
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: "production"
            - name: STATE_FILE
              value: /data/aggregator-db
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bluesky-firehose-data
